--
-- Dumping data for table `categories`
--

/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` VALUES (1,2,'Corruption'),(2,2,'Election'),(3,2,'Government performance'),(4,2,'Unemployment'),(5,2,'Education'),(6,2,'Education'),(7,2,'Political parties'),(8,2,'Agyapa'),(9,2,'Agriculture'),(10,2,'Wages,income and salaries'),(11,2,'Water supply'),(12,2,'Electricity'),(13,2,'Health'),(14,2,'Infrastructure/Roads'),(15,2,'Eurobond'),(16,2,'ESG bonds/financing'),(17,2,'MOF'),(18,2,'Tax'),(19,2,'GRA'),(20,2,'2021 budget'),(21,2,'Petroleum funds'),(22,2,'2021 mid year review'),(23,2,'CBG'),(24,2,'The Competition'),(25,2,'Regulators'),(26,2,'Fix The Country'),(27,2,'Development Bank Ghana'),(28,2,'GSE');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;


--
-- Dumping data for table `keywords`
--

/*!40000 ALTER TABLE `keywords` DISABLE KEYS */;
INSERT INTO `keywords` VALUES (1,1,'whistleblow,solicit,launder,nepotism,kickback,illicit,embezzle,extortion,cronysim,collusion,conflict of interest,bureaucra,corrupt,corrupted,secret,secrecy,corruption,steal,bribe,audit,favouritism,fraud'),(2,2,'opposition,manifesto,candidate,cabinet,ballot,constituenc,poll,parlimentary,campaign,delegate,election,vote,elect'),(3,3,'good government,bad government,government,govern'),(4,4,'employ,job,recruit,career,jobless,hire,hiri,cutback,fired,work'),(5,5,'school,education,students,universit,shs,jhs,high school,class,jss,sss,student,bece,waec,exam'),(6,6,'school,education,students,universit,shs,jhs,high school,class,jss,sss,student,bece,waec,exam'),(7,7,'political parties,ndc,national democratic congress,npp,national patriotic party,cpp,conventions peoples party,apc,dfp,dpp,gnp,ghana national party,ndp,national democratic party'),(8,8,'agyapa,royalties'),(9,9,'agric,farming,planting'),(10,10,'wages,salary,salaries,income,savings,invest'),(11,11,'gwcl,water,taps,pipe'),(12,12,'ecg,electric,dumsor'),(13,13,'health,hospital'),(14,14,'road,infrastructure,infras,potholes'),(15,15,'eurobond,'),(16,16,'ESG bonds,green loans'),(17,17,'mof,ken ofori-attah,ministry of finance,call center,call centre'),(18,18,'vat,value added tax,income tax,tolls,tariffs,tax,new levy,covid'),(19,19,'gra,ghana revenue,Ghana Revenue Authority'),(20,20,'2021 budget'),(21,21,'petroleum funds'),(22,22,'2021 review'),(23,23,'cbg,Consolidated Bank of Ghana'),(24,24,'gcb,fidelity,stanbic,ecobank,unibank, zenith, absa, Société Générale Ghana Ltd, SG-SSB, Guaranty Trust Bank Ghana Limited, Standard Chartered Ghana, Standard Chartered Bank'),(25,25,'bank of ghana,bog'),(26,26,'fix country,galamsey,sanitation,salar,fixthecountry,fix'),(27,27,'National Investment Bank, Financial sector cleanup, Ghana Beyond aid, 170million Euro loan, Ghanas borrowing,loot, European Investment Bank, collapsed banks'),(28,28,'Ghana Stock Exchange, GSE, bear market, bull market, earnings per share, dividend, bid, ask, spread, close price, leverage, margin, initial public offering, IPO, Investment, Investment in Ghana, Best Investment in Ghana, Best Investment in Africa, Invest, Opportunities in Ghana, Make money in Ghana, Make Money, How to Make Money in Ghana, How to Make Money in Africa, Share market, Stock exchange, Over the counter, Liquidity,Trading Volume,Trading Value,Market Capitalization, Index, Mutual Funds, ETF, Exchange Traded Funds, Portfolio, Intra-day Trading, Dividends, OTC, Stock, Share, Order, Volatility, Short sell, Treasury bills, Bonds, Ghana Alternative Market (GAX), Ghana Fixed Income Market (GFIM), Government of Ghana Notes and Bonds, Repo, Collateralized Repo,  Global Master repurchase Agreement (GMRA), Moving average, Haircut, Beta, Savings, Finance, Equities, Securities, Year to date return, Capital Market, Ghana Stock Exchange, Bourse, free shs, national security, Digitisation, SME, Financial Literacy, forex');
/*!40000 ALTER TABLE `keywords` ENABLE KEYS */;

